In [2]:
# Common Optimizers
#  1. SGD
# 2. ADAM OPTIMIZER





# 1. SGD (Stochastic Gradient Descent)
# optimizer = torch.optim.SGD(
#     model.parameters(),
#     lr=0.01
# )

# Formula:

# lr = learning rate 

# W = W - lr × gradient

# Pros:

# Simple
# Less memory

# Cons:

# Can be slow






# 2. SGD with Momentum


# optimizer = torch.optim.SGD(
#     model.parameters(),
#     lr=0.01,
#     momentum=0.9
# )

# Adds velocity:

# Previous direction + Current gradient

# Benefits:

# Faster convergence
# Less oscillation








# 3. Adam (Most Popular)
# optimizer = torch.optim.Adam(
#     model.parameters(),
#     lr=0.001
# )

# Advantages:

# Fast

# Adaptive learning rate

# Works well for most tasks

# Used in:

# CNN
# RNN
# LSTM
# Transformers
# BERT
# GPT







# 4. AdamW
# optimizer = torch.optim.AdamW(
#     model.parameters(),
#     lr=0.001
# )

# Improved Adam with weight decay.

# Commonly used for:

# Transformers
# BERT
# LLMs
# Vision Transformers






# 5. RMSprop
# optimizer = torch.optim.RMSprop(
#     model.parameters(),
#     lr=0.001
# )

# Often used in:

# RNN
# LSTM
# Time-Series
# Viewing Model Parameters
# for param in model.parameters():
#     print(param)

# Optimizer updates these parameters.

# Example
# import torch
# import torch.nn as nn
# import torch.optim as optim

# model = nn.Linear(3, 1)

# optimizer = optim.Adam(
#     model.parameters(),
#     lr=0.001
# )

# loss_fn = nn.MSELoss()

# x = torch.randn(10, 3)
# y = torch.randn(10, 1)

# pred = model(x)

# loss = loss_fn(pred, y)

# optimizer.zero_grad()

# loss.backward()

# optimizer.step()
# Most Used Optimizers in Practice
# Optimizer	Typical Use
# SGD	Basic ML, research
# SGD + Momentum	CNNs
# Adam	General Deep Learning
# AdamW	Transformers, LLMs
# RMSprop	RNNs, LSTMs
# Quick Rule
# Beginner Projects → Adam
# Computer Vision → Adam or SGD+Momentum
# Transformers/LLMs → AdamW

In [4]:
import torch
import torch.nn as nn

relu = nn.ReLU()   
                   #  -ve ====> 0
                   # +ve =====> +ve

x = torch.tensor([-2., 3.])

print(relu(x))

tensor([0., 3.])


In [5]:
sigmoid = nn.Sigmoid()

                      # value in between 0 and 1
print(sigmoid(torch.tensor([0.])))

tensor([0.5000])


In [6]:
tanh = nn.Tanh()
                         # valuein between 1 and -1
print(tanh(torch.tensor([1.])))

tensor([0.7616])


In [7]:
# Raw outputs (logits)
logits = torch.tensor([2.0, 1.0, 0.5])

# Softmax
softmax = nn.Softmax(dim=0)

probabilities = softmax(logits)

print(probabilities)   




# used for the mutliclassess

tensor([0.6285, 0.2312, 0.1402])
