In [1]:
import torch 

In [4]:
x = torch.rand(10, 3)  # random function
print(x)

tensor([[0.1471, 0.0837, 0.3157],
        [0.0965, 0.6095, 0.9377],
        [0.2349, 0.8859, 0.5840],
        [0.4783, 0.8949, 0.0838],
        [0.2958, 0.6876, 0.6779],
        [0.7160, 0.9990, 0.4937],
        [0.9598, 0.7195, 0.1106],
        [0.4157, 0.9192, 0.6787],
        [0.6765, 0.5246, 0.9861],
        [0.3561, 0.5352, 0.2560]])


Pytorch Interview Questions

In [8]:
scaler = torch.tensor(5)
print(scaler)

tensor(5)


In [9]:
vector = torch.tensor([3,2,4])
print(vector)

tensor([3, 2, 4])


In [11]:
matrix = torch.tensor([[3,2,4],[3,5,7],[5,6,7]])
print(matrix)

tensor([[3, 2, 4],
        [3, 5, 7],
        [5, 6, 7]])


In [12]:
torch.rand(3,2)

tensor([[0.5722, 0.2552],
        [0.2437, 0.5443],
        [0.1653, 0.6804]])

In [ ]:
torch.