In [3]:
import torch 

In [ ]:
x = torch.rand(10, 3)  # random function
print(x)

tensor([[0.1471, 0.0837, 0.3157],
        [0.0965, 0.6095, 0.9377],
        [0.2349, 0.8859, 0.5840],
        [0.4783, 0.8949, 0.0838],
        [0.2958, 0.6876, 0.6779],
        [0.7160, 0.9990, 0.4937],
        [0.9598, 0.7195, 0.1106],
        [0.4157, 0.9192, 0.6787],
        [0.6765, 0.5246, 0.9861],
        [0.3561, 0.5352, 0.2560]])


Pytorch Interview Questions

In [8]:
scaler = torch.tensor(5)
print(scaler)

tensor(5)


In [9]:
vector = torch.tensor([3,2,4])
print(vector)

tensor([3, 2, 4])


In [11]:
matrix = torch.tensor([[3,2,4],[3,5,7],[5,6,7]])
print(matrix)

tensor([[3, 2, 4],
        [3, 5, 7],
        [5, 6, 7]])


In [12]:
torch.rand(3,2)

tensor([[0.5722, 0.2552],
        [0.2437, 0.5443],
        [0.1653, 0.6804]])

In [13]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.ones(5,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [15]:
torch.randn(3,3)

tensor([[ 1.8994, -0.8883,  0.1915],
        [ 2.3447,  1.0352, -0.0997],
        [-0.3838,  0.1150, -0.6228]])

In [17]:
device = torch.device("cuda")  #pytoch allowed used the NVIDIA GPU ====> CUDA

What is Autograd?

Autograd automatically calculates gradients during backpropagation.

In [20]:
x = torch.tensor(2.0, requires_grad=True)
print(x)

tensor(2., requires_grad=True)


In [23]:
x = torch.tensor(2.0, requires_grad=True)

y = x**3

y.backward()

print(x.grad)

tensor(12.)


In [27]:
torch.is_complex(torch.tensor([1, 2, 3], dtype=torch.complex128))
torch.is_complex(torch.tensor([1, 2, 3], dtype=torch.int32))
torch.is_complex(torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16))

False

In [29]:
torch.is_complex(torch.tensor([1, 2, 3], dtype=torch.complex64))

True

In [4]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(tensor)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


In [6]:
# Check number of dimensions for TENSOR
tensor.ndim

3

In [7]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)

tensor([[0.0272, 0.3804, 0.4120, 0.9832],
        [0.1170, 0.4831, 0.6742, 0.2863],
        [0.4553, 0.3570, 0.4619, 0.0048]])


In [9]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor

tensor([[[0.2852, 0.4492, 0.7917],
         [0.9678, 0.6117, 0.2250],
         [0.9291, 0.4586, 0.9620],
         ...,
         [0.5784, 0.5115, 0.5968],
         [0.6208, 0.9282, 0.7651],
         [0.7417, 0.0458, 0.1127]],

        [[0.6013, 0.7950, 0.8389],
         [0.5595, 0.0711, 0.6236],
         [0.3054, 0.6130, 0.1185],
         ...,
         [0.1976, 0.1618, 0.5330],
         [0.7806, 0.4628, 0.5787],
         [0.3594, 0.7789, 0.3487]],

        [[0.9744, 0.4391, 0.2949],
         [0.4597, 0.5731, 0.6941],
         [0.7796, 0.1521, 0.1223],
         ...,
         [0.4140, 0.0702, 0.2007],
         [0.9292, 0.1362, 0.7738],
         [0.1275, 0.8445, 0.5837]],

        ...,

        [[0.5992, 0.1446, 0.9562],
         [0.2524, 0.7444, 0.7275],
         [0.5574, 0.7838, 0.6272],
         ...,
         [0.1470, 0.1042, 0.1971],
         [0.0881, 0.9261, 0.1639],
         [0.3067, 0.2205, 0.9558]],

        [[0.9010, 0.3883, 0.9471],
         [0.0741, 0.5679, 0.2718],
         [0.